package view;

import java.sql.*;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Koneksi;

public class LaporanPendapatanPenjualan extends javax.swing.JFrame {
    DefaultTableModel TblLaporanPenjualan;
    DefaultTableModel TblLaporanPenjualanMAX;
    
    /**
     * Creates new form LaporanPendapatanPenjualan
     */
    public LaporanPendapatanPenjualan() {
        initComponents();
        
        tampilTanggal();
        tabelAwalKosong();
        tabelAwalKosong2();
    }
    
    public void tabelAwalKosong() {
        int baris = 0;
        Object kolom[] = {"No", "Tanggal Penjualan", "Total Pendapatan"};
        TblLaporanPenjualan = new DefaultTableModel(kolom, baris);
        
        TabelLaporanPendapatanPenjualan.setModel(TblLaporanPenjualan);
//        
//        TabelLaporanPendapatanPenjualan.getColumnModel().getColumn(0).setPreferredWidth(10);
//        TabelLaporanPendapatanPenjualan.getColumnModel().getColumn(1).setPreferredWidth(200);
//        TabelLaporanPendapatanPenjualan.getColumnModel().getColumn(2).setPreferredWidth(150);
//        TabelLaporanPendapatanPenjualan.getColumnModel().getColumn(3).setPreferredWidth(150);
    }
    
    public void tabelAwalKosong2() {
        int baris = 0;
        Object kolom[] = {"No", "Kode Transaksi", "Tanggal Penjualan", "Pendapatan Maksimum Per Barang", "Total Pendapatan Transaksi", "Nama Pegawai"};
        TblLaporanPenjualanMAX = new DefaultTableModel(kolom, baris);
        
        TabelLaporanPendapatanPenjualanMAX.setModel(TblLaporanPenjualanMAX);
//        
        TabelLaporanPendapatanPenjualanMAX.getColumnModel().getColumn(0).setPreferredWidth(10);
        TabelLaporanPendapatanPenjualanMAX.getColumnModel().getColumn(1).setPreferredWidth(120);
        TabelLaporanPendapatanPenjualanMAX.getColumnModel().getColumn(2).setPreferredWidth(100);
        TabelLaporanPendapatanPenjualanMAX.getColumnModel().getColumn(3).setPreferredWidth(200);
        TabelLaporanPendapatanPenjualanMAX.getColumnModel().getColumn(4).setPreferredWidth(200);
        TabelLaporanPendapatanPenjualanMAX.getColumnModel().getColumn(5).setPreferredWidth(150);
    }
    
    public void tampilTanggal() {
        java.util.Date tgl = new java.util.Date();
        DTanggal.setDate(tgl);
        DTanggal3.setDate(tgl);
        DTanggal1.setDate(tgl);
        DTanggal2.setDate(tgl);
        DTanggal4.setDate(tgl);
        DTanggal5.setDate(tgl);
        DTanggal6.setDate(tgl);
        DTanggal7.setDate(tgl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DTanggal = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelLaporanPendapatanPenjualan = new javax.swing.JTable();
        GenerateTanggal = new javax.swing.JButton();
        GenerateBulan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DTanggal2 = new com.toedter.calendar.JDateChooser();
        DTanggal1 = new com.toedter.calendar.JDateChooser();
        GeneratePeriodik = new javax.swing.JButton();
        BtnBersihkanTabel = new javax.swing.JButton();
        DTanggal3 = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DTanggal4 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        DTanggal5 = new com.toedter.calendar.JDateChooser();
        GenerateBulanMAX = new javax.swing.JButton();
        GenerateTanggalMAX = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        DTanggal6 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        DTanggal7 = new com.toedter.calendar.JDateChooser();
        GeneratePeriodikMAX = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelLaporanPendapatanPenjualanMAX = new javax.swing.JTable();
        BtnBersihkanTabelMAX = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Laporan Pendapatan Transaksi Penjualan");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(33, 158, 188));
        jPanel1.setPreferredSize(new java.awt.Dimension(295, 75));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Laporan Pendapatan Transaksi Penjualan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(21, 21, 21))
        );

        jLabel3.setText("Tanggal");
        jLabel3.setPreferredSize(new java.awt.Dimension(42, 18));

        DTanggal.setDateFormatString("dd MMMM yyyy");

        jLabel4.setText("Bulan");
        jLabel4.setPreferredSize(new java.awt.Dimension(42, 18));

        TabelLaporanPendapatanPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabelLaporanPendapatanPenjualan);

        GenerateTanggal.setText("Generate Data");
        GenerateTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateTanggalActionPerformed(evt);
            }
        });

        GenerateBulan.setText("Generate Data");
        GenerateBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateBulanActionPerformed(evt);
            }
        });

        jLabel5.setText("Dari Tanggal");
        jLabel5.setPreferredSize(new java.awt.Dimension(42, 18));

        jLabel6.setText("Sampai Tanggal");
        jLabel6.setPreferredSize(new java.awt.Dimension(42, 18));

        DTanggal2.setDateFormatString("dd MMMM yyyy");

        DTanggal1.setDateFormatString("dd MMMM yyyy");

        GeneratePeriodik.setText("Generate Data");
        GeneratePeriodik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneratePeriodikActionPerformed(evt);
            }
        });

        BtnBersihkanTabel.setText("Bersihkan Tabel");
        BtnBersihkanTabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBersihkanTabelActionPerformed(evt);
            }
        });

        DTanggal3.setDateFormatString("MMMM yyyy");

        jPanel2.setBackground(new java.awt.Color(33, 158, 188));
        jPanel2.setPreferredSize(new java.awt.Dimension(295, 75));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Laporan Pendapatan Maksimum Per Transaksi Penjualan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(21, 21, 21))
        );

        jLabel7.setText("Tanggal");
        jLabel7.setPreferredSize(new java.awt.Dimension(42, 18));

        DTanggal4.setDateFormatString("dd MMMM yyyy");

        jLabel8.setText("Bulan");
        jLabel8.setPreferredSize(new java.awt.Dimension(42, 18));

        DTanggal5.setDateFormatString("MMMM yyyy");

        GenerateBulanMAX.setText("Generate Data");
        GenerateBulanMAX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateBulanMAXActionPerformed(evt);
            }
        });

        GenerateTanggalMAX.setText("Generate Data");
        GenerateTanggalMAX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateTanggalMAXActionPerformed(evt);
            }
        });

        jLabel9.setText("Dari Tanggal");
        jLabel9.setPreferredSize(new java.awt.Dimension(42, 18));

        DTanggal6.setDateFormatString("dd MMMM yyyy");

        jLabel10.setText("Sampai Tanggal");
        jLabel10.setPreferredSize(new java.awt.Dimension(42, 18));

        DTanggal7.setDateFormatString("dd MMMM yyyy");

        GeneratePeriodikMAX.setText("Generate Data");
        GeneratePeriodikMAX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneratePeriodikMAXActionPerformed(evt);
            }
        });

        TabelLaporanPendapatanPenjualanMAX.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TabelLaporanPendapatanPenjualanMAX);

        BtnBersihkanTabelMAX.setText("Bersihkan Tabel");
        BtnBersihkanTabelMAX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBersihkanTabelMAXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1066, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(GenerateTanggal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DTanggal3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(GenerateBulan)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DTanggal2, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(DTanggal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GeneratePeriodik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnBersihkanTabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1066, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DTanggal4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(GenerateTanggalMAX))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DTanggal5, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(GenerateBulanMAX)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DTanggal7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DTanggal6, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GeneratePeriodikMAX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnBersihkanTabelMAX, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnBersihkanTabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GeneratePeriodik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GenerateTanggal, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GenerateBulan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DTanggal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DTanggal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DTanggal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnBersihkanTabelMAX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GeneratePeriodikMAX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GenerateTanggalMAX, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GenerateBulanMAX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DTanggal6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DTanggal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DTanggal7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DTanggal5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GenerateTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateTanggalActionPerformed
        // TODO add your handling code here:
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(fm.format(DTanggal.getDate()));

        Connection conn = Koneksi.koneksiDB();
        
        int baris = 0;
        Object kolom[] = {"No", "Tanggal Penjualan", "Total Pendapatan"};
        TblLaporanPenjualan = new DefaultTableModel(kolom, baris);

        TblLaporanPenjualan.getDataVector().removeAllElements();

        try {
            Statement stmt = conn.createStatement();
            String query = "SELECT p.tgl_penjualan, SUM(p.total_harga) AS total_pendapatan "
                    + "FROM penjualan p "
                    + "WHERE p.tgl_penjualan = '"+ tanggal +"' "
                    + "GROUP BY p.tgl_penjualan";
            ResultSet rs = stmt.executeQuery(query);
            if (rs.next()) {
                int no = 1;
                do {
                    Object[] data = {
                        no,
                        rs.getString("tgl_penjualan"),
                        rs.getString("total_pendapatan")
                    };
                    TblLaporanPenjualan.addRow(data);
                    no++;
                } while (rs.next());
                TabelLaporanPendapatanPenjualan.setModel(TblLaporanPenjualan);
            } else {
                tabelAwalKosong();
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan");
            }
        } catch(Exception e) {

        }
    }//GEN-LAST:event_GenerateTanggalActionPerformed

    private void GenerateBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateBulanActionPerformed
        // TODO add your handling code here:
        String tampilan = "MM";
        String tampilan2 = "YYYY";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        SimpleDateFormat fm2 = new SimpleDateFormat(tampilan2);
        String bulan = String.valueOf(fm.format(DTanggal3.getDate()));
        String tahun = String.valueOf(fm2.format(DTanggal3.getDate()));
        
        Connection conn = Koneksi.koneksiDB();
        
        int baris = 0;
        Object kolom[] = {"No", "Bulan", "Total Pendapatan"};
        TblLaporanPenjualan = new DefaultTableModel(kolom, baris);

        TblLaporanPenjualan.getDataVector().removeAllElements();

        try {
            Statement stmt = conn.createStatement();
            String query = "SELECT MONTHNAME(p.tgl_penjualan) as bulan, SUM(p.total_harga) AS total_pendapatan "
                    + "FROM penjualan p "
                    + "WHERE MONTH(p.tgl_penjualan) = '"+ bulan +"' AND YEAR(p.tgl_penjualan) = '"+ tahun +"' "
                    + "GROUP BY MONTH(p.tgl_penjualan)";
            ResultSet rs = stmt.executeQuery(query);
            if (rs.next()) {
                int no = 1;
                do {
                    Object[] data = {
                        no,
                        rs.getString("bulan"),
                        rs.getString("total_pendapatan")
                    };
                    TblLaporanPenjualan.addRow(data);
                    no++;
                } while (rs.next());
                TabelLaporanPendapatanPenjualan.setModel(TblLaporanPenjualan);
            } else {
                tabelAwalKosong();
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan");
            }
        } catch(Exception e) {

        }
    }//GEN-LAST:event_GenerateBulanActionPerformed

    private void GeneratePeriodikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneratePeriodikActionPerformed
        // TODO add your handling code here:
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal1 = String.valueOf(fm.format(DTanggal1.getDate()));
        String tanggal2 = String.valueOf(fm.format(DTanggal2.getDate()));

        Connection conn = Koneksi.koneksiDB();
        
        int baris = 0;
        Object kolom[] = {"No", "Tanggal Penjualan", "Total Pendapatan"};
        TblLaporanPenjualan = new DefaultTableModel(kolom, baris);

        TblLaporanPenjualan.getDataVector().removeAllElements();

        try {
            Statement stmt = conn.createStatement();
            String query = "SELECT p.tgl_penjualan, SUM(p.total_harga) AS total_pendapatan "
                    + "FROM penjualan p "
                    + "WHERE p.tgl_penjualan BETWEEN '"+ tanggal1 +"' AND '"+ tanggal2 +"' "
                    + "GROUP BY p.tgl_penjualan";
            ResultSet rs = stmt.executeQuery(query);
            if (rs.next()) {
                int no = 1;
                do {
                    Object[] data = {
                        no,
                        rs.getString("tgl_penjualan"),
                        rs.getString("total_pendapatan")
                    };
                    TblLaporanPenjualan.addRow(data);
                    no++;
                } while (rs.next());
                TabelLaporanPendapatanPenjualan.setModel(TblLaporanPenjualan);
            } else {
                tabelAwalKosong();
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan");
            }
        } catch(Exception e) {

        }
    }//GEN-LAST:event_GeneratePeriodikActionPerformed

    private void BtnBersihkanTabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBersihkanTabelActionPerformed
        // TODO add your handling code here:
        tabelAwalKosong();
    }//GEN-LAST:event_BtnBersihkanTabelActionPerformed

    private void GenerateBulanMAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateBulanMAXActionPerformed
        // TODO add your handling code here:
        String tampilan = "MM";
        String tampilan2 = "YYYY";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        SimpleDateFormat fm2 = new SimpleDateFormat(tampilan2);
        String bulan = String.valueOf(fm.format(DTanggal5.getDate()));
        String tahun = String.valueOf(fm2.format(DTanggal5.getDate()));
        
        Connection conn = Koneksi.koneksiDB();

        TblLaporanPenjualanMAX.getDataVector().removeAllElements();

        try {
            Statement stmt = conn.createStatement();
            String query = "SELECT p.kode_transaksi_penjualan, p.tgl_penjualan, MAX(dp.total_harga) as pendapatan_maksimum, "
                    + "SUM(dp.total_harga) as total_pendapatan, pg.nama_pegawai "
                    + "FROM penjualan p INNER JOIN pegawai pg ON p.kode_pegawai = pg.kode_pegawai "
                    + "INNER JOIN detail_penjualan dp ON p.kode_transaksi_penjualan = dp.kode_transaksi_penjualan "
                    + "WHERE MONTH(p.tgl_penjualan) = '"+ bulan +"' AND YEAR(p.tgl_penjualan) = '"+ tahun +"' "
                    + "GROUP BY dp.kode_transaksi_penjualan";
            ResultSet rs = stmt.executeQuery(query);
            if (rs.next()) {
                int no = 1;
                do {
                    Object[] data = {
                        no,
                        rs.getString("kode_transaksi_penjualan"),
                        rs.getString("tgl_penjualan"),
                        rs.getString("pendapatan_maksimum"),
                        rs.getString("total_pendapatan"),
                        rs.getString("nama_pegawai")
                    };
                    TblLaporanPenjualanMAX.addRow(data);
                    no++;
                } while (rs.next());
                TabelLaporanPendapatanPenjualanMAX.setModel(TblLaporanPenjualanMAX);
            } else {
                tabelAwalKosong2();
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan");
            }
        } catch(Exception e) {

        }
    }//GEN-LAST:event_GenerateBulanMAXActionPerformed

    private void GenerateTanggalMAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateTanggalMAXActionPerformed
        // TODO add your handling code here:
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(fm.format(DTanggal4.getDate()));

        Connection conn = Koneksi.koneksiDB();

        TblLaporanPenjualanMAX.getDataVector().removeAllElements();

        try {
            Statement stmt = conn.createStatement();
            String query = "SELECT p.kode_transaksi_penjualan, p.tgl_penjualan, MAX(dp.total_harga) as pendapatan_maksimum, "
                    + "SUM(dp.total_harga) as total_pendapatan, pg.nama_pegawai "
                    + "FROM penjualan p INNER JOIN pegawai pg ON p.kode_pegawai = pg.kode_pegawai "
                    + "INNER JOIN detail_penjualan dp ON p.kode_transaksi_penjualan = dp.kode_transaksi_penjualan "
                    + "WHERE p.tgl_penjualan = '"+ tanggal +"' "
                    + "GROUP BY dp.kode_transaksi_penjualan";
            ResultSet rs = stmt.executeQuery(query);
            if (rs.next()) {
                int no = 1;
                do {
                    Object[] data = {
                        no,
                        rs.getString("kode_transaksi_penjualan"),
                        rs.getString("tgl_penjualan"),
                        rs.getString("pendapatan_maksimum"),
                        rs.getString("total_pendapatan"),
                        rs.getString("nama_pegawai")
                    };
                    TblLaporanPenjualanMAX.addRow(data);
                    no++;
                } while (rs.next());
                TabelLaporanPendapatanPenjualanMAX.setModel(TblLaporanPenjualanMAX);
            } else {
                tabelAwalKosong2();
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan");
            }
        } catch(Exception e) {

        }
    }//GEN-LAST:event_GenerateTanggalMAXActionPerformed

    private void GeneratePeriodikMAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneratePeriodikMAXActionPerformed
        // TODO add your handling code here:
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal1 = String.valueOf(fm.format(DTanggal6.getDate()));
        String tanggal2 = String.valueOf(fm.format(DTanggal7.getDate()));
        
        Connection conn = Koneksi.koneksiDB();

        TblLaporanPenjualanMAX.getDataVector().removeAllElements();

        try {
            Statement stmt = conn.createStatement();
            String query = "SELECT p.kode_transaksi_penjualan, p.tgl_penjualan, MAX(dp.total_harga) as pendapatan_maksimum, "
                    + "SUM(dp.total_harga) as total_pendapatan, pg.nama_pegawai "
                    + "FROM penjualan p INNER JOIN pegawai pg ON p.kode_pegawai = pg.kode_pegawai "
                    + "INNER JOIN detail_penjualan dp ON p.kode_transaksi_penjualan = dp.kode_transaksi_penjualan "
                    + "WHERE p.tgl_penjualan BETWEEN '"+ tanggal1 +"' AND '"+ tanggal2 +"'"
                    + "GROUP BY dp.kode_transaksi_penjualan";
            ResultSet rs = stmt.executeQuery(query);
            if (rs.next()) {
                int no = 1;
                do {
                    Object[] data = {
                        no,
                        rs.getString("kode_transaksi_penjualan"),
                        rs.getString("tgl_penjualan"),
                        rs.getString("pendapatan_maksimum"),
                        rs.getString("total_pendapatan"),
                        rs.getString("nama_pegawai")
                    };
                    TblLaporanPenjualanMAX.addRow(data);
                    no++;
                } while (rs.next());
                TabelLaporanPendapatanPenjualanMAX.setModel(TblLaporanPenjualanMAX);
            } else {
                tabelAwalKosong2();
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan");
            }
        } catch(Exception e) {

        }
    }//GEN-LAST:event_GeneratePeriodikMAXActionPerformed

    private void BtnBersihkanTabelMAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBersihkanTabelMAXActionPerformed
        // TODO add your handling code here:
        tabelAwalKosong2();
    }//GEN-LAST:event_BtnBersihkanTabelMAXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanPendapatanPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanPendapatanPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanPendapatanPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanPendapatanPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanPendapatanPenjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBersihkanTabel;
    private javax.swing.JButton BtnBersihkanTabelMAX;
    private com.toedter.calendar.JDateChooser DTanggal;
    private com.toedter.calendar.JDateChooser DTanggal1;
    private com.toedter.calendar.JDateChooser DTanggal2;
    private com.toedter.calendar.JDateChooser DTanggal3;
    private com.toedter.calendar.JDateChooser DTanggal4;
    private com.toedter.calendar.JDateChooser DTanggal5;
    private com.toedter.calendar.JDateChooser DTanggal6;
    private com.toedter.calendar.JDateChooser DTanggal7;
    private javax.swing.JButton GenerateBulan;
    private javax.swing.JButton GenerateBulanMAX;
    private javax.swing.JButton GeneratePeriodik;
    private javax.swing.JButton GeneratePeriodikMAX;
    private javax.swing.JButton GenerateTanggal;
    private javax.swing.JButton GenerateTanggalMAX;
    private javax.swing.JTable TabelLaporanPendapatanPenjualan;
    private javax.swing.JTable TabelLaporanPendapatanPenjualanMAX;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
