package view;

import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Koneksi;
import model.LaporanPembelianBarang;

public class LaporanPembelian extends javax.swing.JFrame {
    DefaultTableModel TblLaporanPembelian;
    DefaultComboBoxModel mdlKode = new DefaultComboBoxModel<>();
   
    public LaporanPembelian() {
        initComponents();
        
        tampilTanggal();
        tampilListKodeTransaksi();
        tabelAwalKosong();
    }
    
    public void tampilTanggal() {
        Date tgl = new Date();
        DTanggal.setDate(tgl);
        DTanggal1.setDate(tgl);
        DTanggal2.setDate(tgl);
    }
    
    public void tampilListKodeTransaksi() {
        mdlKode.removeAllElements();
        
        String [] listKodeTransaksi = LaporanPembelianBarang.getListKodeTransaksi();
        for (int i = 0; i < listKodeTransaksi.length; i++) {
            mdlKode.addElement(listKodeTransaksi[i]);
        }
        ComboKode.setModel(mdlKode);
    }
    
    public void tabelAwalKosong() {
        int baris = 0;
        Object kolom[] = {"No", "Kode Transaksi", "Tanggal Penjualan", "Kode Barang", "Nama Barang", "Kategori Barang", 
            "Harga", "Jumlah", "Total Harga", "Nama Supplier", "Nama Pegawai"};
        TblLaporanPembelian = new DefaultTableModel(kolom, baris);
        
        TabelLaporanPembelian.setModel(TblLaporanPembelian);
        
        TabelLaporanPembelian.getColumnModel().getColumn(0).setPreferredWidth(10);
        TabelLaporanPembelian.getColumnModel().getColumn(1).setPreferredWidth(120);
        TabelLaporanPembelian.getColumnModel().getColumn(2).setPreferredWidth(90);
        TabelLaporanPembelian.getColumnModel().getColumn(3).setPreferredWidth(60);
        TabelLaporanPembelian.getColumnModel().getColumn(4).setPreferredWidth(205);
        TabelLaporanPembelian.getColumnModel().getColumn(5).setPreferredWidth(90);
        TabelLaporanPembelian.getColumnModel().getColumn(6).setPreferredWidth(50);
        TabelLaporanPembelian.getColumnModel().getColumn(7).setPreferredWidth(50);
        TabelLaporanPembelian.getColumnModel().getColumn(8).setPreferredWidth(70);
        TabelLaporanPembelian.getColumnModel().getColumn(9).setPreferredWidth(100);
        TabelLaporanPembelian.getColumnModel().getColumn(10).setPreferredWidth(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DTanggal = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        ComboKode = new javax.swing.JComboBox<>();
        GenerateTanggal = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        DTanggal1 = new com.toedter.calendar.JDateChooser();
        GeneratePeriodik = new javax.swing.JButton();
        DTanggal2 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelLaporanPembelian = new javax.swing.JTable();
        GenerateKode = new javax.swing.JButton();
        BtnBersihkanTabel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Laporan Transaksi Pembelian");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(33, 158, 188));
        jPanel1.setPreferredSize(new java.awt.Dimension(295, 75));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Laporan Transaksi Pembelian");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel3.setText("Tanggal");
        jLabel3.setPreferredSize(new java.awt.Dimension(42, 18));

        DTanggal.setDateFormatString("dd MMMM yyyy");

        jLabel4.setText("Kode Transaksi");
        jLabel4.setPreferredSize(new java.awt.Dimension(42, 18));

        ComboKode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        GenerateTanggal.setText("Generate Data");
        GenerateTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateTanggalActionPerformed(evt);
            }
        });

        jLabel5.setText("Dari Tanggal");
        jLabel5.setPreferredSize(new java.awt.Dimension(42, 18));

        DTanggal1.setDateFormatString("dd MMMM yyyy");

        GeneratePeriodik.setText("Generate Data");
        GeneratePeriodik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneratePeriodikActionPerformed(evt);
            }
        });

        DTanggal2.setDateFormatString("dd MMMM yyyy");

        jLabel6.setText("Sampai Tanggal");
        jLabel6.setPreferredSize(new java.awt.Dimension(42, 18));

        TabelLaporanPembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabelLaporanPembelian);

        GenerateKode.setText("Generate Data");
        GenerateKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateKodeActionPerformed(evt);
            }
        });

        BtnBersihkanTabel.setText("Bersihkan Tabel");
        BtnBersihkanTabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBersihkanTabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1298, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(GenerateTanggal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ComboKode, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(GenerateKode)))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DTanggal2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DTanggal1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GeneratePeriodik)
                        .addGap(18, 18, 18)
                        .addComponent(BtnBersihkanTabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnBersihkanTabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GeneratePeriodik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GenerateTanggal, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(GenerateKode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ComboKode)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(DTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(DTanggal1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DTanggal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBersihkanTabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBersihkanTabelActionPerformed
        // TODO add your handling code here:
        tabelAwalKosong();
    }//GEN-LAST:event_BtnBersihkanTabelActionPerformed

    private void GenerateTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateTanggalActionPerformed
        // TODO add your handling code here:
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(fm.format(DTanggal.getDate()));
        
        Connection conn = Koneksi.koneksiDB();
        
        TblLaporanPembelian.getDataVector().removeAllElements();

        try {
            Statement stmt = conn.createStatement();
            String query = "SELECT p.kode_transaksi_pembelian, p.tgl_pembelian, b.kode_barang, b.nama_barang, kb.nama_kategori, "
                    + "b.harga_barang, dp.jumlah, dp.total_harga, s.nama_supplier, pg.nama_pegawai "
                    + "FROM pembelian p "
                    + "INNER JOIN detail_pembelian dp ON p.kode_transaksi_pembelian = dp.kode_transaksi_pembelian "
                    + "INNER JOIN barang b ON b.kode_barang = dp.kode_barang "
                    + "INNER JOIN kategori_barang kb ON kb.kode_kategori = b.kode_kategori "
                    + "INNER JOIN supplier s ON s.kode_supplier = b.kode_supplier "
                    + "INNER JOIN pegawai pg ON p.kode_pegawai = pg.kode_pegawai "
                    + "WHERE p.tgl_pembelian = '"+ tanggal +"' "
                    + "ORDER BY p.kode_transaksi_pembelian ASC";
            ResultSet rs = stmt.executeQuery(query);
            if (rs.next()) {
                int no = 1;
                do {
                    Object[] data = {
                        no,
                        rs.getString("kode_transaksi_pembelian"),
                        rs.getString("tgl_pembelian"),
                        rs.getString("kode_barang"),
                        rs.getString("nama_barang"),
                        rs.getString("nama_kategori"),
                        rs.getString("harga_barang"),
                        rs.getString("jumlah"),
                        rs.getString("total_harga"),
                        rs.getString("nama_supplier"),
                        rs.getString("nama_pegawai"),
                    };
                    TblLaporanPembelian.addRow(data);
                    no++;
                } while (rs.next());
                TabelLaporanPembelian.setModel(TblLaporanPembelian);
            } else {
                tabelAwalKosong();
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan");
            }
        } catch(Exception e) {
            
        }
    }//GEN-LAST:event_GenerateTanggalActionPerformed

    private void GenerateKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateKodeActionPerformed
        // TODO add your handling code here:
        String kodeTransaksi = ComboKode.getSelectedItem().toString();
        
        TblLaporanPembelian.getDataVector().removeAllElements();
        
        String [][] data = LaporanPembelianBarang.getLaporanPembelianByKodeTransaksi(kodeTransaksi);
        for (int i = 0; i < data.length; i++) {
            int no = i + 1;
            TblLaporanPembelian.addRow(new Object[]{no, data[i][0], data[i][1], data[i][2], data[i][3], data[i][4], data[i][5], data[i][6], data[i][7], data[i][8], data[i][9]});
        }
        
        TabelLaporanPembelian.setModel(TblLaporanPembelian);
    }//GEN-LAST:event_GenerateKodeActionPerformed

    private void GeneratePeriodikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneratePeriodikActionPerformed
        // TODO add your handling code here:
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal1 = String.valueOf(fm.format(DTanggal1.getDate()));
        String tanggal2 = String.valueOf(fm.format(DTanggal2.getDate()));
        
        Connection conn = Koneksi.koneksiDB();
        
        TblLaporanPembelian.getDataVector().removeAllElements();
        
        try {
            Statement stmt = conn.createStatement();
            String query = "SELECT p.kode_transaksi_pembelian, p.tgl_pembelian, b.kode_barang, b.nama_barang, kb.nama_kategori, "
                    + "b.harga_barang, dp.jumlah, dp.total_harga, s.nama_supplier, pg.nama_pegawai "
                    + "FROM pembelian p "
                    + "INNER JOIN detail_pembelian dp ON p.kode_transaksi_pembelian = dp.kode_transaksi_pembelian "
                    + "INNER JOIN barang b ON b.kode_barang = dp.kode_barang "
                    + "INNER JOIN kategori_barang kb ON kb.kode_kategori = b.kode_kategori "
                    + "INNER JOIN supplier s ON s.kode_supplier = b.kode_supplier "
                    + "INNER JOIN pegawai pg ON p.kode_pegawai = pg.kode_pegawai "
                    + "WHERE p.tgl_pembelian BETWEEN '"+ tanggal1 +"' AND '"+ tanggal2 +"' "
                    + "ORDER BY p.kode_transaksi_pembelian ASC";
            ResultSet rs = stmt.executeQuery(query);
            if (rs.next()) {
               int no = 1;
               do {
                    Object[] data = {
                        no,
                        rs.getString("kode_transaksi_pembelian"),
                        rs.getString("tgl_pembelian"),
                        rs.getString("kode_barang"),
                        rs.getString("nama_barang"),
                        rs.getString("nama_kategori"),
                        rs.getString("harga_barang"),
                        rs.getString("jumlah"),
                        rs.getString("total_harga"),
                        rs.getString("nama_supplier"),
                        rs.getString("nama_pegawai"),
                    };
                    TblLaporanPembelian.addRow(data);
                    no++;
                } while (rs.next());
                TabelLaporanPembelian.setModel(TblLaporanPembelian);
            } else {
                tabelAwalKosong();
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan");
            }
        } catch(Exception e) {
            
        }
    }//GEN-LAST:event_GeneratePeriodikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanPembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBersihkanTabel;
    private javax.swing.JComboBox<String> ComboKode;
    private com.toedter.calendar.JDateChooser DTanggal;
    private com.toedter.calendar.JDateChooser DTanggal1;
    private com.toedter.calendar.JDateChooser DTanggal2;
    private javax.swing.JButton GenerateKode;
    private javax.swing.JButton GeneratePeriodik;
    private javax.swing.JButton GenerateTanggal;
    private javax.swing.JTable TabelLaporanPembelian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
