package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import model.Pegawai;
import model.UserLogin;

public class MenuUtama extends javax.swing.JFrame {
    
    String kodePegawai = UserLogin.getKodePegawai();
    
    public MenuUtama() {
        initComponents();
        hakAkses();
        tampilJam();
        tampilTanggal();
        String [][] data = Pegawai.getDataPegawaiByKode(kodePegawai);
        LblOperator.setText(data[0][2]);
        LblRole.setText(data[0][9]);
    }
    
    public void hakAkses() {
        String [][] data = Pegawai.getDataPegawaiByKode(kodePegawai);
        String idRole = data[0][8];
        int IDRole = Integer.parseInt(idRole);
        
        if(IDRole == 2) {
            MenuMaster.setEnabled(true);
            MenuKategoriBarang.setEnabled(false);
            MenuPegawai.setEnabled(false);
            MenuSupplier.setEnabled(false);
            MenuLaporan.setEnabled(false);
            BtnBarang.setEnabled(true);
            BtnKategori.setEnabled(false);
            BtnPegawai.setEnabled(false);
            BtnSupplier.setEnabled(false);
            BtnLaporanPenjualan.setEnabled(false);
            BtnLaporanPembelian.setEnabled(false);
            BtnLaporanPendapatanPenjualan.setEnabled(false);
        }
    }
    
    public void tampilJam(){
        ActionListener taskPerformer = new ActionListener() {
 
        @Override
            public void actionPerformed(ActionEvent evt) {
            String nol_jam = "", nol_menit = "",nol_detik = "";
 
            java.util.Date dateTime = new java.util.Date();
            int nilai_jam = dateTime.getHours();
            int nilai_menit = dateTime.getMinutes();
            int nilai_detik = dateTime.getSeconds();
 
            if(nilai_jam <= 9) nol_jam= "0";
            if(nilai_menit <= 9) nol_menit= "0";
            if(nilai_detik <= 9) nol_detik= "0";
 
            String jam = nol_jam + Integer.toString(nilai_jam);
            String menit = nol_menit + Integer.toString(nilai_menit);
            String detik = nol_detik + Integer.toString(nilai_detik);
 
            LblJam.setText(jam+":"+menit+":"+detik+"");
            }
        };
        new Timer(1000, taskPerformer).start();
    }
    
    public void tampilTanggal() {
        java.util.Date tglsekarang = new java.util.Date();
        SimpleDateFormat smpdtfmt = new SimpleDateFormat("dd MMMM yyyy", Locale.getDefault());
        String tanggal = smpdtfmt.format(tglsekarang);
        LblTanggal.setText(tanggal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JSeparator();
        TabPane = new javax.swing.JTabbedPane();
        ToolBarMaster = new javax.swing.JToolBar();
        BtnBarang = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        BtnKategori = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        BtnPegawai = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        BtnSupplier = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        ToolBarTransaksi = new javax.swing.JToolBar();
        BtnPenjualan = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        BtnPembelian = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        ToolBarLaporan = new javax.swing.JToolBar();
        BtnLaporanPenjualan = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        BtnLaporanPembelian = new javax.swing.JButton();
        BtnLaporanPendapatanPenjualan = new javax.swing.JButton();
        ToolBarSetting = new javax.swing.JToolBar();
        BtnEditProfil = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        BtnLogout = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        BtnKeluar = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        jToolBar1 = new javax.swing.JToolBar();
        BtnProfilKelompok = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LblOperator = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LblTanggal = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        LblJam = new javax.swing.JLabel();
        LblOperator1 = new javax.swing.JLabel();
        LblRole = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuMaster = new javax.swing.JMenu();
        MenuBarang = new javax.swing.JMenuItem();
        MenuKategoriBarang = new javax.swing.JMenuItem();
        MenuPegawai = new javax.swing.JMenuItem();
        MenuSupplier = new javax.swing.JMenuItem();
        MenuTransaksi = new javax.swing.JMenu();
        MenuPenjualan = new javax.swing.JMenuItem();
        MenuPembelian = new javax.swing.JMenuItem();
        MenuLaporan = new javax.swing.JMenu();
        MenuLaporanPenjualan = new javax.swing.JMenuItem();
        MenuLaporanPembelian = new javax.swing.JMenuItem();
        MenuLaporanPendapatanPenjualan = new javax.swing.JMenuItem();
        MenuSetting = new javax.swing.JMenu();
        MenuEditProfil = new javax.swing.JMenuItem();
        MenuLogout = new javax.swing.JMenuItem();
        MenuKeluar = new javax.swing.JMenuItem();
        MenuAbout = new javax.swing.JMenu();
        MenuProfilKelompok = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu Utama");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        ToolBarMaster.setFloatable(false);
        ToolBarMaster.setRollover(true);

        BtnBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/barang.png"))); // NOI18N
        BtnBarang.setText("Barang");
        BtnBarang.setFocusable(false);
        BtnBarang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnBarang.setMaximumSize(new java.awt.Dimension(63, 59));
        BtnBarang.setMinimumSize(new java.awt.Dimension(63, 59));
        BtnBarang.setPreferredSize(new java.awt.Dimension(63, 59));
        BtnBarang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBarangActionPerformed(evt);
            }
        });
        ToolBarMaster.add(BtnBarang);
        ToolBarMaster.add(jSeparator1);

        BtnKategori.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/kategori.png"))); // NOI18N
        BtnKategori.setText("Kategori");
        BtnKategori.setFocusable(false);
        BtnKategori.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnKategori.setMaximumSize(new java.awt.Dimension(63, 59));
        BtnKategori.setMinimumSize(new java.awt.Dimension(63, 59));
        BtnKategori.setPreferredSize(new java.awt.Dimension(63, 59));
        BtnKategori.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKategoriActionPerformed(evt);
            }
        });
        ToolBarMaster.add(BtnKategori);
        ToolBarMaster.add(jSeparator2);

        BtnPegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/users.png"))); // NOI18N
        BtnPegawai.setText("Pegawai");
        BtnPegawai.setFocusable(false);
        BtnPegawai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnPegawai.setMaximumSize(new java.awt.Dimension(63, 59));
        BtnPegawai.setMinimumSize(new java.awt.Dimension(63, 59));
        BtnPegawai.setPreferredSize(new java.awt.Dimension(63, 59));
        BtnPegawai.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPegawaiActionPerformed(evt);
            }
        });
        ToolBarMaster.add(BtnPegawai);
        ToolBarMaster.add(jSeparator3);

        BtnSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/supplier.png"))); // NOI18N
        BtnSupplier.setText("Supplier");
        BtnSupplier.setFocusable(false);
        BtnSupplier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnSupplier.setMaximumSize(new java.awt.Dimension(63, 59));
        BtnSupplier.setMinimumSize(new java.awt.Dimension(63, 59));
        BtnSupplier.setPreferredSize(new java.awt.Dimension(63, 59));
        BtnSupplier.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSupplierActionPerformed(evt);
            }
        });
        ToolBarMaster.add(BtnSupplier);
        ToolBarMaster.add(jSeparator4);

        TabPane.addTab("Master Data", ToolBarMaster);

        ToolBarTransaksi.setFloatable(false);
        ToolBarTransaksi.setRollover(true);

        BtnPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/penjualan.png"))); // NOI18N
        BtnPenjualan.setText("Penjualan");
        BtnPenjualan.setFocusable(false);
        BtnPenjualan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnPenjualan.setMaximumSize(new java.awt.Dimension(63, 59));
        BtnPenjualan.setMinimumSize(new java.awt.Dimension(63, 59));
        BtnPenjualan.setPreferredSize(new java.awt.Dimension(64, 59));
        BtnPenjualan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPenjualanActionPerformed(evt);
            }
        });
        ToolBarTransaksi.add(BtnPenjualan);
        ToolBarTransaksi.add(jSeparator6);

        BtnPembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pembelian.png"))); // NOI18N
        BtnPembelian.setText("Pembelian");
        BtnPembelian.setFocusable(false);
        BtnPembelian.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnPembelian.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPembelianActionPerformed(evt);
            }
        });
        ToolBarTransaksi.add(BtnPembelian);
        ToolBarTransaksi.add(jSeparator7);

        TabPane.addTab("Transaksi", ToolBarTransaksi);

        ToolBarLaporan.setFloatable(false);
        ToolBarLaporan.setRollover(true);

        BtnLaporanPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/laporan3.png"))); // NOI18N
        BtnLaporanPenjualan.setText("Penjualan");
        BtnLaporanPenjualan.setFocusable(false);
        BtnLaporanPenjualan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnLaporanPenjualan.setMaximumSize(new java.awt.Dimension(63, 59));
        BtnLaporanPenjualan.setMinimumSize(new java.awt.Dimension(63, 59));
        BtnLaporanPenjualan.setPreferredSize(new java.awt.Dimension(64, 59));
        BtnLaporanPenjualan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnLaporanPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLaporanPenjualanActionPerformed(evt);
            }
        });
        ToolBarLaporan.add(BtnLaporanPenjualan);
        ToolBarLaporan.add(jSeparator11);

        BtnLaporanPembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/laporan4.png"))); // NOI18N
        BtnLaporanPembelian.setText("Pembelian");
        BtnLaporanPembelian.setFocusable(false);
        BtnLaporanPembelian.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnLaporanPembelian.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnLaporanPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLaporanPembelianActionPerformed(evt);
            }
        });
        ToolBarLaporan.add(BtnLaporanPembelian);

        BtnLaporanPendapatanPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/laporan2.png"))); // NOI18N
        BtnLaporanPendapatanPenjualan.setText("Pendapatan Penjualan");
        BtnLaporanPendapatanPenjualan.setFocusable(false);
        BtnLaporanPendapatanPenjualan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnLaporanPendapatanPenjualan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnLaporanPendapatanPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLaporanPendapatanPenjualanActionPerformed(evt);
            }
        });
        ToolBarLaporan.add(BtnLaporanPendapatanPenjualan);

        TabPane.addTab("Laporan", ToolBarLaporan);

        ToolBarSetting.setFloatable(false);
        ToolBarSetting.setRollover(true);

        BtnEditProfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit2.png"))); // NOI18N
        BtnEditProfil.setText("Edit Profil");
        BtnEditProfil.setFocusable(false);
        BtnEditProfil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnEditProfil.setMaximumSize(new java.awt.Dimension(63, 59));
        BtnEditProfil.setMinimumSize(new java.awt.Dimension(63, 59));
        BtnEditProfil.setPreferredSize(new java.awt.Dimension(63, 59));
        BtnEditProfil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnEditProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditProfilActionPerformed(evt);
            }
        });
        ToolBarSetting.add(BtnEditProfil);
        ToolBarSetting.add(jSeparator9);

        BtnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        BtnLogout.setText("Logout");
        BtnLogout.setFocusable(false);
        BtnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnLogout.setMaximumSize(new java.awt.Dimension(63, 59));
        BtnLogout.setMinimumSize(new java.awt.Dimension(63, 59));
        BtnLogout.setPreferredSize(new java.awt.Dimension(63, 59));
        BtnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogoutActionPerformed(evt);
            }
        });
        ToolBarSetting.add(BtnLogout);
        ToolBarSetting.add(jSeparator8);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/power-off (1).png"))); // NOI18N
        BtnKeluar.setText("Keluar");
        BtnKeluar.setFocusable(false);
        BtnKeluar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnKeluar.setMaximumSize(new java.awt.Dimension(63, 59));
        BtnKeluar.setMinimumSize(new java.awt.Dimension(63, 59));
        BtnKeluar.setPreferredSize(new java.awt.Dimension(63, 59));
        BtnKeluar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        ToolBarSetting.add(BtnKeluar);
        ToolBarSetting.add(jSeparator10);

        TabPane.addTab("Setting & Keluar", ToolBarSetting);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        BtnProfilKelompok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/role.png"))); // NOI18N
        BtnProfilKelompok.setText("Profil Kelompok");
        BtnProfilKelompok.setFocusable(false);
        BtnProfilKelompok.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnProfilKelompok.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnProfilKelompok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProfilKelompokActionPerformed(evt);
            }
        });
        jToolBar1.add(BtnProfilKelompok);

        TabPane.addTab("About", jToolBar1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Operator");

        jLabel2.setText(":");

        LblOperator.setText("Administrator");

        jLabel5.setText(":");

        jLabel4.setText("Tanggal");

        LblTanggal.setText("26 November 2022");

        jLabel10.setText("Jam");

        jLabel11.setText(":");

        LblJam.setText("19:30:00");

        LblOperator1.setText("--");

        LblRole.setText("Role Pegawai");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblOperator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblOperator1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblRole)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblTanggal)
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblJam)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(LblTanggal))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(LblJam))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(LblOperator)
                        .addComponent(LblOperator1)
                        .addComponent(LblRole)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MenuMaster.setText("Master Data");

        MenuBarang.setText("Data Barang");
        MenuBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBarangActionPerformed(evt);
            }
        });
        MenuMaster.add(MenuBarang);

        MenuKategoriBarang.setText("Data Kategori Barang");
        MenuKategoriBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuKategoriBarangActionPerformed(evt);
            }
        });
        MenuMaster.add(MenuKategoriBarang);

        MenuPegawai.setText("Data Pegawai");
        MenuPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPegawaiActionPerformed(evt);
            }
        });
        MenuMaster.add(MenuPegawai);

        MenuSupplier.setText("Data Supplier");
        MenuSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSupplierActionPerformed(evt);
            }
        });
        MenuMaster.add(MenuSupplier);

        jMenuBar1.add(MenuMaster);

        MenuTransaksi.setText("Transaksi");

        MenuPenjualan.setText("Penjualan");
        MenuPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPenjualanActionPerformed(evt);
            }
        });
        MenuTransaksi.add(MenuPenjualan);

        MenuPembelian.setText("Pembelian");
        MenuPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPembelianActionPerformed(evt);
            }
        });
        MenuTransaksi.add(MenuPembelian);

        jMenuBar1.add(MenuTransaksi);

        MenuLaporan.setText("Laporan");

        MenuLaporanPenjualan.setText("Penjualan");
        MenuLaporanPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLaporanPenjualanActionPerformed(evt);
            }
        });
        MenuLaporan.add(MenuLaporanPenjualan);

        MenuLaporanPembelian.setText("Pembelian");
        MenuLaporanPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLaporanPembelianActionPerformed(evt);
            }
        });
        MenuLaporan.add(MenuLaporanPembelian);

        MenuLaporanPendapatanPenjualan.setText("Pendapatan Penjualan");
        MenuLaporanPendapatanPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLaporanPendapatanPenjualanActionPerformed(evt);
            }
        });
        MenuLaporan.add(MenuLaporanPendapatanPenjualan);

        jMenuBar1.add(MenuLaporan);

        MenuSetting.setText("Setting & Keluar");

        MenuEditProfil.setText("Edit Profil");
        MenuEditProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEditProfilActionPerformed(evt);
            }
        });
        MenuSetting.add(MenuEditProfil);

        MenuLogout.setText("Logout");
        MenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLogoutActionPerformed(evt);
            }
        });
        MenuSetting.add(MenuLogout);

        MenuKeluar.setText("Keluar");
        MenuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuKeluarActionPerformed(evt);
            }
        });
        MenuSetting.add(MenuKeluar);

        jMenuBar1.add(MenuSetting);

        MenuAbout.setText("About");

        MenuProfilKelompok.setText("Profil Kelompok");
        MenuProfilKelompok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProfilKelompokActionPerformed(evt);
            }
        });
        MenuAbout.add(MenuProfilKelompok);

        jMenuBar1.add(MenuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabPane, javax.swing.GroupLayout.DEFAULT_SIZE, 883, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 312, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(MenuUtama.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void BtnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBarangActionPerformed
        // TODO add your handling code here:
        DataBarang dataBarang = new DataBarang();
        dataBarang.setVisible(true);
    }//GEN-LAST:event_BtnBarangActionPerformed

    private void BtnKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKategoriActionPerformed
        // TODO add your handling code here:
        DataKategori dataKategori = new DataKategori();
        dataKategori.setVisible(true);
    }//GEN-LAST:event_BtnKategoriActionPerformed

    private void BtnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSupplierActionPerformed
        // TODO add your handling code here:
        DataSupplier dataSupplier = new DataSupplier();
        dataSupplier.setVisible(true);
    }//GEN-LAST:event_BtnSupplierActionPerformed

    private void MenuBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBarangActionPerformed
        // TODO add your handling code here:
        DataBarang dataBarang = new DataBarang();
        dataBarang.setVisible(true);
    }//GEN-LAST:event_MenuBarangActionPerformed

    private void MenuKategoriBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuKategoriBarangActionPerformed
        // TODO add your handling code here:
        DataKategori dataKategori = new DataKategori();
        dataKategori.setVisible(true);
    }//GEN-LAST:event_MenuKategoriBarangActionPerformed

    private void MenuPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPegawaiActionPerformed
        // TODO add your handling code here:
        DataPegawai dataPegawai = new DataPegawai();
        dataPegawai.setVisible(true);
    }//GEN-LAST:event_MenuPegawaiActionPerformed

    private void MenuSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSupplierActionPerformed
        // TODO add your handling code here:
        DataSupplier dataSupplier = new DataSupplier();
        dataSupplier.setVisible(true);
    }//GEN-LAST:event_MenuSupplierActionPerformed

    private void BtnPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPegawaiActionPerformed
        // TODO add your handling code here:
        DataPegawai dataPegawai = new DataPegawai();
        dataPegawai.setVisible(true);
    }//GEN-LAST:event_BtnPegawaiActionPerformed

    private void BtnPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPenjualanActionPerformed
        // TODO add your handling code here:
        Penjualan penjualan = new Penjualan();
        penjualan.setVisible(true);
    }//GEN-LAST:event_BtnPenjualanActionPerformed

    private void BtnPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPembelianActionPerformed
        // TODO add your handling code here:
        Pembelian pembelian = new Pembelian();
        pembelian.setVisible(true);
    }//GEN-LAST:event_BtnPembelianActionPerformed

    private void MenuPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPenjualanActionPerformed
        // TODO add your handling code here:
        Penjualan penjualan = new Penjualan();
        penjualan.setVisible(true);
    }//GEN-LAST:event_MenuPenjualanActionPerformed

    private void MenuPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPembelianActionPerformed
        // TODO add your handling code here:
        Pembelian pembelian = new Pembelian();
        pembelian.setVisible(true);
    }//GEN-LAST:event_MenuPembelianActionPerformed

    private void BtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogoutActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Apakah anda yakin akan ingin Logout dari Aplikasi?", "Konfirmasi",
            JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE) == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            Login login = new Login();
            login.setVisible(true);
            UserLogin.setKodePegawai("");
            JOptionPane.showMessageDialog(null, "Anda berhasil Logout", "Pesan Berhasil", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BtnLogoutActionPerformed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Apakah anda yakin akan ingin Keluar dari Aplikasi?", "Konfirmasi",
            JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE) == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            JOptionPane.showMessageDialog(null, "Anda berhasil keluar dari aplikasi", "Pesan Berhasil", JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnEditProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditProfilActionPerformed
        // TODO add your handling code here:
        EditProfil editProfil = new EditProfil();
        editProfil.setVisible(true);
    }//GEN-LAST:event_BtnEditProfilActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Apakah anda yakin akan ingin keluar dari Aplikasi?", "Konfirmasi",
            JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE) == JOptionPane.YES_OPTION) {
            UserLogin.setKodePegawai("");
            this.setVisible(false);
            Login login = new Login();
            login.setLocationRelativeTo(this);
            login.setVisible(true);
            JOptionPane.showMessageDialog(null, "Anda berhasil Logout", "Pesan Berhasil", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void MenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLogoutActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Apakah anda yakin akan ingin Logout dari Aplikasi?", "Konfirmasi",
            JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE) == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            Login login = new Login();
            login.setVisible(true);
            UserLogin.setKodePegawai("");
            JOptionPane.showMessageDialog(null, "Anda berhasil Logout", "Pesan Berhasil", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_MenuLogoutActionPerformed

    private void MenuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuKeluarActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Apakah anda yakin akan ingin Keluar dari Aplikasi?", "Konfirmasi",
            JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE) == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            JOptionPane.showMessageDialog(null, "Anda berhasil keluar dari aplikasi", "Pesan Berhasil", JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
    }//GEN-LAST:event_MenuKeluarActionPerformed

    private void MenuEditProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEditProfilActionPerformed
        // TODO add your handling code here:
        EditProfil editProfil = new EditProfil();
        editProfil.setVisible(true);
    }//GEN-LAST:event_MenuEditProfilActionPerformed

    private void BtnLaporanPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLaporanPenjualanActionPerformed
        // TODO add your handling code here:
        LaporanPenjualan laporanPenjualan = new LaporanPenjualan();
        laporanPenjualan.setVisible(true);
    }//GEN-LAST:event_BtnLaporanPenjualanActionPerformed

    private void BtnLaporanPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLaporanPembelianActionPerformed
        // TODO add your handling code here:
        LaporanPembelian laporanPembelian = new LaporanPembelian();
        laporanPembelian.setVisible(true);
    }//GEN-LAST:event_BtnLaporanPembelianActionPerformed

    private void MenuLaporanPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLaporanPenjualanActionPerformed
        // TODO add your handling code here:
        LaporanPenjualan laporanPenjualan = new LaporanPenjualan();
        laporanPenjualan.setVisible(true);
    }//GEN-LAST:event_MenuLaporanPenjualanActionPerformed

    private void MenuLaporanPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLaporanPembelianActionPerformed
        // TODO add your handling code here:
        LaporanPembelian laporanPembelian = new LaporanPembelian();
        laporanPembelian.setVisible(true);
    }//GEN-LAST:event_MenuLaporanPembelianActionPerformed

    private void MenuProfilKelompokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProfilKelompokActionPerformed
        // TODO add your handling code here:
        ProfilKelompok profilKelompok = new ProfilKelompok();
        profilKelompok.setVisible(true);
    }//GEN-LAST:event_MenuProfilKelompokActionPerformed

    private void BtnProfilKelompokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProfilKelompokActionPerformed
        // TODO add your handling code here:
        ProfilKelompok profilKelompok = new ProfilKelompok();
        profilKelompok.setVisible(true);
    }//GEN-LAST:event_BtnProfilKelompokActionPerformed

    private void BtnLaporanPendapatanPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLaporanPendapatanPenjualanActionPerformed
        // TODO add your handling code here:
        LaporanPendapatanPenjualan lPP = new LaporanPendapatanPenjualan();
        lPP.setVisible(true);
    }//GEN-LAST:event_BtnLaporanPendapatanPenjualanActionPerformed

    private void MenuLaporanPendapatanPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLaporanPendapatanPenjualanActionPerformed
        // TODO add your handling code here:
        LaporanPendapatanPenjualan lPP = new LaporanPendapatanPenjualan();
        lPP.setVisible(true);
    }//GEN-LAST:event_MenuLaporanPendapatanPenjualanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBarang;
    private javax.swing.JButton BtnEditProfil;
    private javax.swing.JButton BtnKategori;
    private javax.swing.JButton BtnKeluar;
    private javax.swing.JButton BtnLaporanPembelian;
    private javax.swing.JButton BtnLaporanPendapatanPenjualan;
    private javax.swing.JButton BtnLaporanPenjualan;
    private javax.swing.JButton BtnLogout;
    private javax.swing.JButton BtnPegawai;
    private javax.swing.JButton BtnPembelian;
    private javax.swing.JButton BtnPenjualan;
    private javax.swing.JButton BtnProfilKelompok;
    private javax.swing.JButton BtnSupplier;
    private javax.swing.JLabel LblJam;
    private javax.swing.JLabel LblOperator;
    private javax.swing.JLabel LblOperator1;
    private javax.swing.JLabel LblRole;
    private javax.swing.JLabel LblTanggal;
    private javax.swing.JMenu MenuAbout;
    private javax.swing.JMenuItem MenuBarang;
    private javax.swing.JMenuItem MenuEditProfil;
    private javax.swing.JMenuItem MenuKategoriBarang;
    private javax.swing.JMenuItem MenuKeluar;
    private javax.swing.JMenu MenuLaporan;
    private javax.swing.JMenuItem MenuLaporanPembelian;
    private javax.swing.JMenuItem MenuLaporanPendapatanPenjualan;
    private javax.swing.JMenuItem MenuLaporanPenjualan;
    private javax.swing.JMenuItem MenuLogout;
    private javax.swing.JMenu MenuMaster;
    private javax.swing.JMenuItem MenuPegawai;
    private javax.swing.JMenuItem MenuPembelian;
    private javax.swing.JMenuItem MenuPenjualan;
    private javax.swing.JMenuItem MenuProfilKelompok;
    private javax.swing.JMenu MenuSetting;
    private javax.swing.JMenuItem MenuSupplier;
    private javax.swing.JMenu MenuTransaksi;
    private javax.swing.JTabbedPane TabPane;
    private javax.swing.JToolBar ToolBarLaporan;
    private javax.swing.JToolBar ToolBarMaster;
    private javax.swing.JToolBar ToolBarSetting;
    private javax.swing.JToolBar ToolBarTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
